---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-home-directory
  labels:
     {{- include "jenkins.labels" . | nindent 4 }}
spec:
  storageClassName: {{.Values.storage.className }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.storage.home_value}}Gi

